import { Tool, ToolIntegration } from '@/src/types';

export const INITIAL_TOOLS: Tool[] = [
  {
    id: "tool-google-search",
    slug: "google-search",
    name: "Google Search API",
    website_url: "https://developers.google.com/custom-search",
    logo_url: "🔍",
    short_description: "Programmatic web search and query indexing.",
    long_description: "Google Custom Search JSON API allows web developers to retrieve and display search results from Google Search programmatically. Excellent for fetching recent news, facts, and website links for AI context.",
    category: "research",
    subcategories: ["Search Engine", "Web Scraper"],
    capabilities: ["web_search", "news_fetching", "link_scraping"],
    best_for: "Fetching real-time accurate information from the web to ground LLM outputs.",
    not_recommended_for: "Deep database queries or batch scanning of specific enterprise records.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 5,
    pricing_currency: "USD",
    pricing_notes: "First 100 queries per day are free. Thereafter, $5 per 1,000 queries.",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["make", "zapier", "n8n", "pipedream"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Web", "Cloud"],
    technical_difficulty: "intermediate",
    no_code_friendly: false,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "Queries may be logged by Google in accordance with API terms of service.",
    supports_india: true,
    reliability_score: 10,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-06-01"
  },
  {
    id: "tool-feedly",
    slug: "feedly",
    name: "Feedly",
    website_url: "https://feedly.com",
    logo_url: "🟢",
    short_description: "News aggregator and RSS content curation platform.",
    long_description: "Feedly is an AI-powered market intelligence and feed aggregation platform. It helps content curators track newsletters, RSS feeds, and blogs in one central workspace.",
    category: "research",
    subcategories: ["Content Curation", "RSS"],
    capabilities: ["rss_feed", "article_monitoring", "newsletter_tracking"],
    best_for: "Monitoring industry blogs, newsletters, and news sources systematically.",
    not_recommended_for: "Natural language conversations or text generation.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 6,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 100 feeds. Paid plans unlock AI Feedly Leo filters starting at $6/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["slack", "make", "zapier", "n8n", "google-sheets"],
    import_formats: ["OPML", "XML"],
    export_formats: ["OPML", "JSON"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "User feeds and boards are retained on Feedly secure cloud.",
    supports_india: true,
    reliability_score: 9,
    editorial_quality_score: 8,
    verification_status: "verified",
    last_verified_at: "2026-05-15"
  },
  {
    id: "tool-perplexity",
    slug: "perplexity",
    name: "Perplexity AI",
    website_url: "https://perplexity.ai",
    logo_url: "🌀",
    short_description: "Conversational answer engine with real-time web search.",
    long_description: "Perplexity AI is an AI-powered search engine that answers natural language queries using citations. Excellent for finding synthesised summaries of complex topics, news, and market data.",
    category: "research",
    subcategories: ["AI Search", "Information Retrieval"],
    capabilities: ["web_search", "text_synthesis", "citation_generation"],
    best_for: "Synthesising vast search queries with real-time citations and sources.",
    not_recommended_for: "Structured database transactions or high-throughput batch task pipelines.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free basic search. Pro plan ($20/mo) unlocks advanced models and files upload.",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["make", "zapier"],
    import_formats: ["TXT", "PDF"],
    export_formats: ["TXT", "PDF"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "Search history is saved in account unless turned off in settings.",
    supports_india: true,
    reliability_score: 9,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-06-10"
  },
  {
    id: "tool-gemini",
    slug: "gemini",
    name: "Google Gemini",
    website_url: "https://ai.google.dev",
    logo_url: "✦",
    short_description: "Google's powerful, multimodal AI model series with large context window.",
    long_description: "Google Gemini is a highly capable family of models featuring advanced multimodal reasoning, text generation, and a ground-breaking context window of up to 2 million tokens. Outstanding for bulk text analyses, translation, and structured data outputs.",
    category: "research",
    subcategories: ["LLM", "Generative AI"],
    capabilities: ["text_generation", "image_understanding", "structured_json_output", "long_context"],
    best_for: "Analysing large PDFs, complex multi-step reasoning, and generating high-quality structured content.",
    not_recommended_for: "Direct desktop application automation without a middleware API.",
    pricing_type: "usage_based",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 0,
    pricing_currency: "INR",
    pricing_notes: "Generous free tier on AI Studio. Pay-as-you-go pricing based on input/output tokens.",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["make", "zapier", "n8n", "pipedream", "github", "vercel"],
    import_formats: ["TXT", "PDF", "Images", "Audio", "Video"],
    export_formats: ["JSON", "TXT"],
    supported_platforms: ["Web", "API"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "API data is not used for model training if using paid/enterprise tiers.",
    supports_india: true,
    reliability_score: 9.5,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-07-01"
  },
  {
    id: "tool-claude",
    slug: "claude",
    name: "Anthropic Claude",
    website_url: "https://anthropic.com/claude",
    logo_url: "✉️",
    short_description: "Claude is a state-of-the-art conversational LLM focused on safety and nuance.",
    long_description: "Anthropic Claude (e.g. Claude 3.5 Sonnet) is an industry-leading model family praised for advanced coding, nuanced creative writing, high-accuracy comprehension, and friendly, natural dialogue.",
    category: "research",
    subcategories: ["LLM", "Generative AI"],
    capabilities: ["text_generation", "coding", "reasoning", "document_analysis"],
    best_for: "Nuanced writing, complex software development, precise text summaries, and critical thinking.",
    not_recommended_for: "Real-time web browsing without search grounding tools.",
    pricing_type: "usage_based",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free tier on web interface. API is charged per million tokens ($3 input / $15 output for Sonnet).",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["make", "zapier", "n8n", "pipedream", "github"],
    import_formats: ["TXT", "PDF", "JSON", "Images"],
    export_formats: ["TXT", "JSON"],
    supported_platforms: ["Web", "API"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Anthropic does not train models on API data. Data is deleted after 30 days unless required for compliance.",
    supports_india: true,
    reliability_score: 9.5,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-07-02"
  },
  {
    id: "tool-chatgpt",
    slug: "chatgpt",
    name: "OpenAI ChatGPT",
    website_url: "https://openai.com",
    logo_url: "🤖",
    short_description: "OpenAI's benchmark generative AI conversational model.",
    long_description: "ChatGPT (GPT-4o) is OpenAI's flagship conversational and multimodal model. Extremely popular, with strong performance in programming, logical operations, translation, and structured data tasks.",
    category: "research",
    subcategories: ["LLM", "Generative AI"],
    capabilities: ["text_generation", "web_browsing", "data_analysis", "image_generation"],
    best_for: "General purpose AI assistance, complex automation, and structured calculations.",
    not_recommended_for: "Locally hosted offline workflows without internet access.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free basic access. Plus is $20/mo. API is priced per-token.",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["make", "zapier", "n8n", "pipedream", "google-sheets", "notion"],
    import_formats: ["CSV", "TXT", "PDF", "Images"],
    export_formats: ["TXT", "JSON", "PNG"],
    supported_platforms: ["Web", "iOS", "Android", "API"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "API data is not trained on. Web app data is trained on unless opted out.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-07-05"
  },
  {
    id: "tool-openrouter",
    slug: "openrouter",
    name: "OpenRouter AI",
    website_url: "https://openrouter.ai",
    logo_url: "🔌",
    short_description: "Unified router and API gateway for dozens of open and closed LLMs.",
    long_description: "OpenRouter provides a standardized API endpoint to access Claude, GPT-4, LLaMA, Gemini, and dozens of other open-source models with competitive, real-time pricing and dynamic fallback management.",
    category: "development",
    subcategories: ["AI Infrastructure", "API Aggregator"],
    capabilities: ["text_generation", "model_routing", "unified_billing"],
    best_for: "Deploying applications that require switching models instantly without updating code.",
    not_recommended_for: "Purely client-side applications without an intermediate server.",
    pricing_type: "usage_based",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 0,
    pricing_currency: "USD",
    pricing_notes: "Charges strictly by token usage based on the underlying model. Includes free access to several open-source models.",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["make", "n8n", "pipedream", "github"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Web", "API"],
    technical_difficulty: "developer",
    no_code_friendly: false,
    open_source: true,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "Routes payloads securely. Data retention subject to underlying model providers selected.",
    supports_india: true,
    reliability_score: 9.3,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-06-25"
  },
  {
    id: "tool-canva",
    slug: "canva",
    name: "Canva Pro",
    website_url: "https://canva.com",
    logo_url: "🎨",
    short_description: "Visual design platform with extensive templates and AI tools.",
    long_description: "Canva is a highly visual, drag-and-drop design platform that simplifies content creation, social media posts, presentation decks, and visual graphics with dynamic templates and AI elements.",
    category: "content_creation",
    subcategories: ["Graphic Design", "Social Assets"],
    capabilities: ["image_editing", "presentation_creation", "video_layout", "ai_image_magic"],
    best_for: "Creating beautiful, branded social media posts, headers, and slides quickly.",
    not_recommended_for: "High-level professional UI vector drawing or database warehousing.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 13,
    pricing_currency: "USD",
    pricing_notes: "Free basic templates. Pro plan ($13/month) unlocks advanced AI and branding kits.",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["slack", "make", "zapier", "buffer"],
    import_formats: ["PNG", "JPG", "PDF", "SVG"],
    export_formats: ["PNG", "JPG", "PDF", "SVG", "MP4"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "All user assets are held securely on Canva cloud servers.",
    supports_india: true,
    reliability_score: 9.7,
    editorial_quality_score: 9.2,
    verification_status: "verified",
    last_verified_at: "2026-05-20"
  },
  {
    id: "tool-recraft",
    slug: "recraft",
    name: "Recraft AI",
    website_url: "https://recraft.ai",
    logo_url: "📐",
    short_description: "Generative AI art board for designers specializing in vector art.",
    long_description: "Recraft AI is an infinite art board designed for visual professionals. It generates beautiful, brand-aligned vectors, icons, and illustrations with fine-grained color palette and style control.",
    category: "content_creation",
    subcategories: ["AI Graphic Design", "Vector Generator"],
    capabilities: ["vector_generation", "style_control", "icon_design", "palette_matching"],
    best_for: "Generating high-quality, scalable SVG graphics and matching visual icons.",
    not_recommended_for: "Bulk text processing, analytical reporting, or raw photograph edits.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free tier generates public images. Paid tier ($20/mo) makes creations private and fast.",
    api_available: true,
    webhooks_available: false,
    direct_integrations: ["make"],
    import_formats: ["PNG", "JPG"],
    export_formats: ["SVG", "PNG", "Lottie"],
    supported_platforms: ["Web", "API"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "Free tier images are publicly viewable on community feeds.",
    supports_india: true,
    reliability_score: 9.2,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-06-15"
  },
  {
    id: "tool-buffer",
    slug: "buffer",
    name: "Buffer",
    website_url: "https://buffer.com",
    logo_url: "📊",
    short_description: "Social media scheduling, publishing, and analytical toolkit.",
    long_description: "Buffer is an easy-to-use publishing platform that schedules posts, manages channels, and tracks analytics for LinkedIn, X, Instagram, Facebook, and Mastodon in a unified calendar.",
    category: "marketing",
    subcategories: ["Social Scheduler", "Analytics"],
    capabilities: ["post_scheduling", "social_publishing", "performance_analytics"],
    best_for: "Planning and scheduling social media posts in batches safely.",
    not_recommended_for: "Drafting the copy or generating content directly (use AI tools for that).",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 6,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 3 social channels and 10 scheduled posts per channel. Paid plan is $6/month per channel.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["canva", "make", "zapier", "n8n"],
    import_formats: ["CSV", "TXT"],
    export_formats: ["CSV", "PDF"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Maintains standard social authorization tokens and post histories.",
    supports_india: true,
    reliability_score: 9.6,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-07-03"
  },
  {
    id: "tool-make",
    slug: "make",
    name: "Make.com",
    website_url: "https://make.com",
    logo_url: "🟣",
    short_description: "Visual automation and integration platform to connect apps.",
    long_description: "Make.com is a visual integration platform that allows users to connect APIs, automate workflows, and design complex pipelines using a rich library of pre-built app integrations with a drag-and-drop builder.",
    category: "productivity",
    subcategories: ["Integration Platform", "Workflow Automation"],
    capabilities: ["webhook_handling", "api_integration", "conditional_routing", "data_mapping"],
    best_for: "No-code and low-code integrations with visual drag-and-drop workflows and multiple steps.",
    not_recommended_for: "Ultra high-speed local script execution or local hardware control.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 9,
    pricing_currency: "USD",
    pricing_notes: "Free plan includes 1,000 operations per month. Core plan starts at $9/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["google-sheets", "slack", "notion", "gmail", "zapier", "hubspot", "stripe", "canva", "perplexity", "gemini", "claude", "chatgpt"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Web", "Cloud"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "SOC2 compliant. Execution logs are stored securely and purged regularly according to settings.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-07-10"
  },
  {
    id: "tool-zapier",
    slug: "zapier",
    name: "Zapier",
    website_url: "https://zapier.com",
    logo_url: "🟠",
    short_description: "The gold standard of simple, pre-built web app automations.",
    long_description: "Zapier connects over 6,000 apps with simple 'if-this-then-that' formulas. High reliability, extensive pre-built catalog, and highly accessible for non-technical users.",
    category: "productivity",
    subcategories: ["Integration Platform", "Workflow Automation"],
    capabilities: ["webhook_handling", "api_integration", "conditional_logic"],
    best_for: "Quickly connecting standard web apps without writing any code.",
    not_recommended_for: "Complex looping, multi-dimensional array transformations, or highly cost-sensitive high-volume tasks.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free plan limited to single-step Zaps (100 tasks/mo). Multi-step Zaps require Starter ($20/mo).",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["google-sheets", "slack", "notion", "gmail", "hubspot", "stripe", "gemini", "claude", "chatgpt"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Web", "Cloud"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Highly secure enterprise privacy. Data is logged purely for task status histories.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.6,
    verification_status: "verified",
    last_verified_at: "2026-07-09"
  },
  {
    id: "tool-n8n",
    slug: "n8n",
    name: "n8n.io",
    website_url: "https://n8n.io",
    logo_url: "🔴",
    short_description: "Fair-code node-based workflow automation, highly self-hostable.",
    long_description: "n8n is an extendable workflow automation tool. It allows users to self-host workflows or use cloud hosting. Features beautiful visual flowcharts and native support for custom JavaScript/Python code nodes.",
    category: "productivity",
    subcategories: ["Integration Platform", "Workflow Automation"],
    capabilities: ["webhook_handling", "api_integration", "code_execution", "self_hosting"],
    best_for: "High-volume automations, complex logic requiring code blocks, and privacy-conscious self-hosting.",
    not_recommended_for: "Absolute beginners who are uncomfortable with hosting or basic JSON formats.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free forever if self-hosted on your own server. Cloud pricing starts at $20/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["google-sheets", "slack", "notion", "gmail", "hubspot", "stripe", "gemini", "claude", "chatgpt", "supabase", "github"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Docker", "Web", "Cloud", "Self-hosted"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: true,
    self_hostable: true,
    privacy_level: "high",
    data_retention_notes: "Self-hosting ensures 100% data ownership. Cloud tier uses encrypted logs.",
    supports_india: true,
    reliability_score: 9.5,
    editorial_quality_score: 9.3,
    verification_status: "verified",
    last_verified_at: "2026-07-08"
  },
  {
    id: "tool-pipedream",
    slug: "pipedream",
    name: "Pipedream",
    website_url: "https://pipedream.com",
    logo_url: "🪵",
    short_description: "Integration platform for developers to connect APIs with Node.js/Python.",
    long_description: "Pipedream is a developer-centric integration platform. It runs serverless triggers and actions, allowing developers to write arbitrary Node.js, Python, or Go code for any integration step.",
    category: "development",
    subcategories: ["Serverless Integration", "API Automation"],
    capabilities: ["webhook_handling", "code_execution", "api_integration"],
    best_for: "Developers who want a managed, serverless environment to bind APIs with custom code.",
    not_recommended_for: "Non-technical users who require a fully graphical, code-free experience.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 29,
    pricing_currency: "USD",
    pricing_notes: "Free plan includes 333 credits/day. Paid plans start at $29/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["google-sheets", "slack", "notion", "github", "gemini", "claude", "chatgpt"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Cloud", "API"],
    technical_difficulty: "developer",
    no_code_friendly: false,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "SOC 2 Type II certified. Data encrypted in transit and rest.",
    supports_india: true,
    reliability_score: 9.7,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-06-20"
  },
  {
    id: "tool-google-sheets",
    slug: "google-sheets",
    name: "Google Sheets",
    website_url: "https://google.com/sheets",
    logo_url: "📗",
    short_description: "Web-based collaborative spreadsheet editor.",
    long_description: "Google Sheets is a cloud-based spreadsheet program. Highly flexible, collaborative, and acts as an immediate, lightweight structured database or CSV queue for automation tools.",
    category: "productivity",
    subcategories: ["Spreadsheet", "Database"],
    capabilities: ["data_storage", "csv_export", "real_time_collaboration"],
    best_for: "Storing raw text outputs, managing queue items, manual logging, and basic data reports.",
    not_recommended_for: "High-performance relational transactions or very large, complex datasets (use SQL).",
    pricing_type: "free",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 0,
    pricing_currency: "INR",
    pricing_notes: "Free for individual accounts. Part of Google Workspace for business users.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["gmail", "make", "zapier", "n8n", "pipedream", "slack"],
    import_formats: ["CSV", "XLSX", "TSV"],
    export_formats: ["CSV", "XLSX", "PDF"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "Secured under standard Google Cloud infrastructure.",
    supports_india: true,
    reliability_score: 10,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-07-01"
  },
  {
    id: "tool-airtable",
    slug: "airtable",
    name: "Airtable",
    website_url: "https://airtable.com",
    logo_url: "🗂️",
    short_description: "Low-code visual relational database and collaboration platform.",
    long_description: "Airtable blends the ease of a spreadsheet with the power of a relational database. It enables building beautiful custom interfaces, custom workflows, and highly structured schema designs.",
    category: "productivity",
    subcategories: ["No-code Database", "Workspace Management"],
    capabilities: ["relational_data", "view_filtering", "form_input", "automation_triggers"],
    best_for: "Managing visual content calendars, structured project logs, and inventory pipelines.",
    not_recommended_for: "High-throughput database reads/writes of millions of records.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free basic plan (up to 1,000 records). Paid plan is $20/month per user.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["slack", "make", "zapier", "n8n", "notion"],
    import_formats: ["CSV", "XLSX"],
    export_formats: ["CSV", "JSON"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Highly secure cloud database with SOC 2 compliance.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.6,
    verification_status: "verified",
    last_verified_at: "2026-07-11"
  },
  {
    id: "tool-notion",
    slug: "notion",
    name: "Notion",
    website_url: "https://notion.so",
    logo_url: "📓",
    short_description: "Connected workspace for notes, wiki, docs, and databases.",
    long_description: "Notion is an all-in-one workspace featuring customizable wikis, rich text notes, project boards, and inline relational databases. Ideal for documentation, shared team lists, and knowledge bases.",
    category: "productivity",
    subcategories: ["Knowledge Base", "Notes", "Database"],
    capabilities: ["document_collaboration", "rich_text", "visual_databases"],
    best_for: "Compiling meeting notes, structured user wikis, custom task organizers, and visual boards.",
    not_recommended_for: "Serving as a fast, low-latency relational database for dynamic web applications.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 8,
    pricing_currency: "USD",
    pricing_notes: "Free for individual usage. Plus starts at $8/month per user for team sharing.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["slack", "make", "zapier", "n8n", "github", "google-sheets"],
    import_formats: ["Markdown", "CSV", "HTML", "DOCX"],
    export_formats: ["Markdown", "PDF", "HTML", "CSV"],
    supported_platforms: ["Web", "Mac", "Windows", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "Workspace data is held securely on Notion's servers.",
    supports_india: true,
    reliability_score: 9.7,
    editorial_quality_score: 9.7,
    verification_status: "verified",
    last_verified_at: "2026-07-12"
  },
  {
    id: "tool-supabase",
    slug: "supabase",
    name: "Supabase",
    website_url: "https://supabase.com",
    logo_url: "⚡",
    short_description: "Open source Firebase alternative providing PostgreSQL database and Auth.",
    long_description: "Supabase is a developer-centric open-source platform that instantly provisions a real PostgreSQL database with full row-level security, instant API generation, database triggers, file storage, and integrated user authentication.",
    category: "development",
    subcategories: ["Database", "Backend as a Service"],
    capabilities: ["sql_relational_data", "user_auth", "real_time_events", "file_storage"],
    best_for: "Production web applications needing a secure, scale-to-zero relational SQL database with authentication.",
    not_recommended_for: "Non-technical users who do not understand schemas, SQL, or web API mechanics.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 25,
    pricing_currency: "USD",
    pricing_notes: "Free tier offers 2 active projects and 500MB DB space. Pro tier starts at $25/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["github", "vercel", "n8n"],
    import_formats: ["SQL", "CSV", "JSON"],
    export_formats: ["SQL", "CSV", "JSON"],
    supported_platforms: ["Cloud", "Self-hosted"],
    technical_difficulty: "developer",
    no_code_friendly: false,
    open_source: true,
    self_hostable: true,
    privacy_level: "high",
    data_retention_notes: "Full Row-Level Security. Data is managed securely on AWS instances under user configuration.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-07-06"
  },
  {
    id: "tool-github",
    slug: "github",
    name: "GitHub",
    website_url: "https://github.com",
    logo_url: "🐙",
    short_description: "Git repository hosting and developer collaboration hub.",
    long_description: "GitHub hosts Git source code repositories and facilitates software versioning, issue tracking, pulls, and automated continuous deployment workflows (GitHub Actions).",
    category: "development",
    subcategories: ["Version Control", "DevOps"],
    capabilities: ["code_repository", "ci_cd_pipelines", "issue_tracking"],
    best_for: "Managing source code, trigger builds, and coordinating engineering task streams.",
    not_recommended_for: "General purpose notes archiving or visually layout creation.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 4,
    pricing_currency: "USD",
    pricing_notes: "Free for unlimited public and private repositories. Copilot and Team features are paid.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["vercel", "slack", "make", "zapier", "n8n", "pipedream", "supabase"],
    import_formats: ["Git"],
    export_formats: ["Git", "ZIP"],
    supported_platforms: ["Web", "Mac", "Windows", "Linux"],
    technical_difficulty: "developer",
    no_code_friendly: false,
    open_source: false,
    self_hostable: true,
    privacy_level: "high",
    data_retention_notes: "Highly compliant SOC 2. Repository privacy options available.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.8,
    verification_status: "verified",
    last_verified_at: "2026-07-04"
  },
  {
    id: "tool-vercel",
    slug: "vercel",
    name: "Vercel",
    website_url: "https://vercel.com",
    logo_url: "▲",
    short_description: "Frontend hosting and serverless functions deployment cloud.",
    long_description: "Vercel is the ultimate deployment platform for frontend frameworks (Next.js, React, Vue). It handles instant global CDN caching, automated Git deployments, serverless APIs, and edge computing.",
    category: "development",
    subcategories: ["Hosting", "Cloud Platform"],
    capabilities: ["web_hosting", "serverless_apis", "analytics"],
    best_for: "Hosting full-stack websites, serverless APIs, and frontend pages with zero-config setup.",
    not_recommended_for: "Persistent running state servers (like continuous game backends or WebSockets).",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free for individual hobby projects. Pro tier starts at $20/month per member.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["github", "supabase", "make", "zapier"],
    import_formats: ["Source Code"],
    export_formats: ["Static Build"],
    supported_platforms: ["Web", "Cloud"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Highly secure edge networks with global compliance standards.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.7,
    verification_status: "verified",
    last_verified_at: "2026-07-05"
  },
  {
    id: "tool-gmail",
    slug: "gmail",
    name: "Gmail (Google Workspace)",
    website_url: "https://workspace.google.com/gmail",
    logo_url: "✉️",
    short_description: "Secure, enterprise-grade business email provider.",
    long_description: "Gmail is Google's ubiquitous emailing platform. Features robust filters, API automation triggers, and connects easily with scheduling and reporting apps.",
    category: "productivity",
    subcategories: ["Email", "Communication"],
    capabilities: ["email_sending", "email_receiving", "labeling"],
    best_for: "Automating newsletters, dispatching customer summaries, and triggering workflows on incoming mail.",
    not_recommended_for: "High-volume promotional spamming (use dedicated tools like Mailchimp or Resend).",
    pricing_type: "free",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 0,
    pricing_currency: "INR",
    pricing_notes: "Free for standard consumer accounts. Business workspace starts at $6/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "pipedream", "google-sheets"],
    import_formats: ["Mbox", "EML"],
    export_formats: ["EML", "JSON"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Strict data privacy under Google Workspace policies.",
    supports_india: true,
    reliability_score: 10,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-07-01"
  },
  {
    id: "tool-slack",
    slug: "slack",
    name: "Slack",
    website_url: "https://slack.com",
    logo_url: "💬",
    short_description: "Real-time communication and channel hub for modern workspaces.",
    long_description: "Slack is a messaging application that organizes communication into channels. Integrates seamlessly with external APIs to deliver real-time automated reports, system alerts, or interactive bot queries.",
    category: "productivity",
    subcategories: ["Team Chat", "Alerts"],
    capabilities: ["channel_alerts", "team_messaging", "slash_commands", "interactive_buttons"],
    best_for: "Sending daily workflow reports, server status alerts, and centralizing team conversations.",
    not_recommended_for: "Serving as a primary client-facing CRM database or document store.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 7,
    pricing_currency: "USD",
    pricing_notes: "Free with 90-day message history limit. Pro tier starts at $7.25/month per seat.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "pipedream", "github", "google-sheets", "notion"],
    import_formats: ["JSON"],
    export_formats: ["JSON", "HTML"],
    supported_platforms: ["Web", "Mac", "Windows", "Linux", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Encrypted in transit and rest. Compliant with HIPAA, SOC2.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.6,
    verification_status: "verified",
    last_verified_at: "2026-07-02"
  },
  {
    id: "tool-hubspot",
    slug: "hubspot",
    name: "HubSpot CRM",
    website_url: "https://hubspot.com",
    logo_url: "🧡",
    short_description: "All-in-one visual CRM, sales pipelines, and customer support tool.",
    long_description: "HubSpot is a comprehensive customer relationship management (CRM) platform that organizes sales tracking, automated email marketing lists, and visual pipeline metrics.",
    category: "sales",
    subcategories: ["CRM", "Sales Automation"],
    capabilities: ["contact_management", "sales_pipeline", "email_sequences"],
    best_for: "Tracking customer leads, automating follow-up emails, and syncing sales workflows.",
    not_recommended_for: "General purpose individual note-taking or serverless coding tasks.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 15,
    pricing_currency: "USD",
    pricing_notes: "Free basic CRM tools. Paid starter marketing packages start at $15/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "slack", "google-sheets"],
    import_formats: ["CSV", "XLSX"],
    export_formats: ["CSV", "XLSX"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Strict enterprise security rules, GDPR and CCPA compliant.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.4,
    verification_status: "verified",
    last_verified_at: "2026-06-28"
  },
  {
    id: "tool-intercom",
    slug: "intercom",
    name: "Intercom",
    website_url: "https://intercom.com",
    logo_url: "🔵",
    short_description: "Live chat platform with automated Fin AI bots for support.",
    long_description: "Intercom is a customer service platform featuring live chat widgets, deep integration triggers, automated workflows, and an AI agent (Fin) designed to resolve customer inquiries instantly.",
    category: "customer_support",
    subcategories: ["Helpdesk", "AI Agent Helpdesk"],
    capabilities: ["live_chat", "ai_ticketing", "customer_history"],
    best_for: "Resolving customer inquiries instantly via smart web bots and live desk queues.",
    not_recommended_for: "High-level database development or source code compiling.",
    pricing_type: "paid",
    free_plan_available: false,
    free_trial_available: true,
    starting_monthly_price: 39,
    pricing_currency: "USD",
    pricing_notes: "No permanent free plan. Starts at $39/month per seat, plus charge per Fin AI resolution.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "slack", "hubspot"],
    import_formats: ["CSV"],
    export_formats: ["CSV", "JSON"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Secure client conversation logs. SOC 2 compliant.",
    supports_india: true,
    reliability_score: 9.7,
    editorial_quality_score: 9.2,
    verification_status: "verified",
    last_verified_at: "2026-06-12"
  },
  {
    id: "tool-freshdesk",
    slug: "freshdesk",
    name: "Freshdesk",
    website_url: "https://freshworks.com/freshdesk",
    logo_url: "🟢",
    short_description: "Intuitive customer support helpdesk and email ticketing system.",
    long_description: "Freshdesk converts customer emails, chats, and calls into managed support tickets. Highly customizable automation triggers, SLA metrics tracking, and agent routing algorithms.",
    category: "customer_support",
    subcategories: ["Helpdesk", "SLA Ticketing"],
    capabilities: ["ticket_routing", "sla_tracking", "automated_notifications"],
    best_for: "Converting support inboxes into structured workflows with clear responsibilities.",
    not_recommended_for: "Continuous high-fidelity visual layout creation.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 15,
    pricing_currency: "USD",
    pricing_notes: "Free plan support for up to 10 agents with email ticketing. Growth plan starts at $15/month per agent.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "slack", "hubspot"],
    import_formats: ["CSV"],
    export_formats: ["CSV", "PDF"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Secured enterprise SaaS hosting. GDPR and ISO compliant.",
    supports_india: true,
    reliability_score: 9.6,
    editorial_quality_score: 9.1,
    verification_status: "verified",
    last_verified_at: "2026-05-18"
  },
  {
    id: "tool-resend",
    slug: "resend",
    name: "Resend",
    website_url: "https://resend.com",
    logo_url: "✉️",
    short_description: "Modern, developer-friendly transactional email delivery service.",
    long_description: "Resend is a premium, developer-optimized API tool to build, test, and send beautiful HTML or plain emails using modern React-email templates. Outstanding deliverability and simple setup.",
    category: "marketing",
    subcategories: ["Transactional Email", "Email API"],
    capabilities: ["email_sending", "html_templates", "bounce_tracking"],
    best_for: "Developers wanting a simple, clean, bulletproof HTML email sending mechanism.",
    not_recommended_for: "Visual non-technical drag-and-drop marketing campaigns.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 20,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 3,000 emails per month. Paid plan starts at $20/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "pipedream"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Cloud", "API"],
    technical_difficulty: "intermediate",
    no_code_friendly: false,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Emails are not stored beyond necessary logs for delivery statuses.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.6,
    verification_status: "verified",
    last_verified_at: "2026-07-02"
  },
  {
    id: "tool-mailchimp",
    slug: "mailchimp",
    name: "Mailchimp",
    website_url: "https://mailchimp.com",
    logo_url: "🐒",
    short_description: "Ubiquitous visual email marketing and newsletter manager.",
    long_description: "Mailchimp provides a highly visual, drag-and-drop builder to capture emails, schedule marketing campaigns, send periodic newsletters, and track visual audience retention metrics.",
    category: "marketing",
    subcategories: ["Email Marketing", "Newsletters"],
    capabilities: ["newsletter_campaigns", "drag_drop_editor", "audience_segmentation"],
    best_for: "Creating beautiful recurring marketing campaigns and managing mailing lists.",
    not_recommended_for: "Purely transactional developer-driven programmatic alerts.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 13,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 500 contacts and 1,000 monthly sends. Paid tier starts at $13/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "google-sheets", "canva", "hubspot"],
    import_formats: ["CSV", "TXT"],
    export_formats: ["CSV", "XLSX"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Secure GDPR-compliant subscriber data retention.",
    supports_india: true,
    reliability_score: 9.7,
    editorial_quality_score: 9.3,
    verification_status: "verified",
    last_verified_at: "2026-06-19"
  },
  {
    id: "tool-stripe",
    slug: "stripe",
    name: "Stripe",
    website_url: "https://stripe.com",
    logo_url: "💳",
    short_description: "Financial infrastructure and online payment gateway.",
    long_description: "Stripe is the leading payment gateway processing internet transactions. Highly robust API, instant checkout generation, subscription management, and webhook alerts for real-time sales tracking.",
    category: "finance",
    subcategories: ["Payment Gateway", "Billing"],
    capabilities: ["payment_processing", "checkout_generation", "subscription_billing"],
    best_for: "Collecting online credit card payments, managing monthly subscriptions, and sending automated invoices.",
    not_recommended_for: "General office task lists or content drafting.",
    pricing_type: "usage_based",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 0,
    pricing_currency: "USD",
    pricing_notes: "No setup or monthly fees. Standard pay-as-you-go rate is 2.9% + 30¢ per successful card charge.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "pipedream", "supabase", "hubspot"],
    import_formats: ["JSON"],
    export_formats: ["CSV", "JSON"],
    supported_platforms: ["Web", "API", "iOS", "Android"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Strict PCI DSS Level 1 compliance. Highly encrypted, financial grade.",
    supports_india: true,
    reliability_score: 10,
    editorial_quality_score: 9.8,
    verification_status: "verified",
    last_verified_at: "2026-07-06"
  },
  {
    id: "tool-razorpay",
    slug: "razorpay",
    name: "Razorpay",
    website_url: "https://razorpay.com",
    logo_url: "💳",
    short_description: "The primary online payments and billing portal in India.",
    long_description: "Razorpay is India's leading payment gateway supporting UPI, netbanking, credit cards, and mobile wallets. Highly developer-friendly APIs and direct webhook syncs.",
    category: "finance",
    subcategories: ["Payment Gateway", "Billing"],
    capabilities: ["upi_payments", "subscription_billing", "payment_links"],
    best_for: "Indian SaaS and e-commerce platforms collecting local payments with native UPI support.",
    not_recommended_for: "International-only global checkout routing with complex currency swaps.",
    pricing_type: "usage_based",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 0,
    pricing_currency: "INR",
    pricing_notes: "No setup fees. Standard rate is 2% per successful transaction (3% for international cards).",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "shopify", "woocommerce"],
    import_formats: ["JSON"],
    export_formats: ["CSV", "JSON"],
    supported_platforms: ["Web", "API", "iOS", "Android"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "PCI-DSS compliant, heavily regulated under Reserve Bank of India mandates.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-06-25"
  },
  {
    id: "tool-webflow",
    slug: "webflow",
    name: "Webflow",
    website_url: "https://webflow.com",
    logo_url: "🕸️",
    short_description: "Professional visual canvas to design and build websites with custom CMS.",
    long_description: "Webflow allows designers to design, build, and publish modern responsive sites using a visual canvas without writing code. Fully integrated CMS and custom databases.",
    category: "development",
    subcategories: ["No-code Site Builder", "CMS"],
    capabilities: ["web_design", "cms_data_collection", "form_submissions"],
    best_for: "Building high-end, responsive marketing landing pages and dynamic websites visually.",
    not_recommended_for: "Heavy raw programming or operating high-concurrency systems.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 14,
    pricing_currency: "USD",
    pricing_notes: "Free workspace to learn. CMS hosting plans start at $14/month paid annually.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "google-sheets"],
    import_formats: ["CSV"],
    export_formats: ["HTML", "CSS", "JSON"],
    supported_platforms: ["Web"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Secure AWS-backed server storage.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.6,
    verification_status: "verified",
    last_verified_at: "2026-07-08"
  },
  {
    id: "tool-shopify",
    slug: "shopify",
    name: "Shopify",
    website_url: "https://shopify.com",
    logo_url: "🛍️",
    short_description: "The benchmark global e-commerce and retail store framework.",
    long_description: "Shopify manages entire online storefronts, inventories, orders, shipping rates, customer carts, and checkout logs programmatically with deep API integration hooks.",
    category: "sales",
    subcategories: ["E-Commerce Store", "Inventory"],
    capabilities: ["order_fulfillment", "product_cataloging", "shopping_carts"],
    best_for: "Creating, maintaining, and scaling standard commercial e-commerce stores.",
    not_recommended_for: "Individual project management tracking or writing source code.",
    pricing_type: "paid",
    free_plan_available: false,
    free_trial_available: true,
    starting_monthly_price: 39,
    pricing_currency: "USD",
    pricing_notes: "Trial is free for 3 days, then $39/month for Basic Shopify. Transaction charges apply if not using Shopify Payments.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "slack", "mailchimp", "stripe"],
    import_formats: ["CSV"],
    export_formats: ["CSV", "JSON"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "High customer data compliance, GDPR-ready, secure databases.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.7,
    verification_status: "verified",
    last_verified_at: "2026-07-03"
  },
  {
    id: "tool-twilio",
    slug: "twilio",
    name: "Twilio API",
    website_url: "https://twilio.com",
    logo_url: "📞",
    short_description: "Unified communication API gateway for SMS, voice, and WhatsApp.",
    long_description: "Twilio allows web developers to dispatch SMS notifications, place automated phone calls, verify OTP passwords, and run WhatsApp bot triggers programmatically with developer APIs.",
    category: "customer_support",
    subcategories: ["Communication API", "SMS Gateway"],
    capabilities: ["sms_sending", "voice_broadcasts", "whatsapp_api"],
    best_for: "Dispatching urgent SMS, OTP passwords, and automating outbound cell phone dispatches.",
    not_recommended_for: "Writing content or serving as an office chat workspace.",
    pricing_type: "usage_based",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 1,
    pricing_currency: "USD",
    pricing_notes: "Pay per sent message (e.g. ~0.79¢ per SMS in US). WhatsApp charges have session premiums.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "pipedream", "google-sheets"],
    import_formats: ["JSON"],
    export_formats: ["JSON"],
    supported_platforms: ["Cloud", "API"],
    technical_difficulty: "developer",
    no_code_friendly: false,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Messages logs are encrypted and can be automatically redacted on completion.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.4,
    verification_status: "verified",
    last_verified_at: "2026-06-30"
  },
  {
    id: "tool-sendgrid",
    slug: "sendgrid",
    name: "Twilio SendGrid",
    website_url: "https://sendgrid.com",
    logo_url: "✉️",
    short_description: "High-volume transactional and marketing email delivery.",
    long_description: "SendGrid is a massive email engine built for reliability. It manages developer transactional emails, visual newsletter signups, domain auth checks, and email bounce metrics.",
    category: "marketing",
    subcategories: ["Transactional Email", "Email Marketing"],
    capabilities: ["email_sending", "marketing_automation", "bounce_analytics"],
    best_for: "Dispatching millions of developer programmatic emails with extreme inbox deliverability.",
    not_recommended_for: "Direct CRM contact mapping without secondary triggers.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 15,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 100 emails per day. Essential tier starts at $15/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["make", "zapier", "n8n", "pipedream"],
    import_formats: ["JSON", "CSV"],
    export_formats: ["JSON", "CSV"],
    supported_platforms: ["Cloud", "API"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Secured under strict enterprise data logs.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.2,
    verification_status: "verified",
    last_verified_at: "2026-06-25"
  },
  {
    id: "tool-jira",
    slug: "jira",
    name: "Jira Software",
    website_url: "https://atlassian.com/software/jira",
    logo_url: "🔷",
    short_description: "Enterprise agile project tracking and issue management.",
    long_description: "Jira is an advanced project management board for engineering teams. Tracks user stories, agile sprints, system bugs, software releases, and connects deeply to code repositories.",
    category: "productivity",
    subcategories: ["Agile Management", "Issue Tracker"],
    capabilities: ["sprint_tracking", "bug_logging", "roadmap_planning"],
    best_for: "Agile software development teams coordinating code milestones and releases.",
    not_recommended_for: "Basic individual shopping checklists (too heavy/complex).",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 8,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 10 users. Paid plans start at $8.15/month per user.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["github", "slack", "make", "zapier", "n8n"],
    import_formats: ["CSV", "JSON"],
    export_formats: ["CSV", "JSON", "XML"],
    supported_platforms: ["Web", "Mac", "Windows", "iOS", "Android"],
    technical_difficulty: "intermediate",
    no_code_friendly: true,
    open_source: false,
    self_hostable: true,
    privacy_level: "high",
    data_retention_notes: "Managed under Atlassian's corporate enterprise security, SOC2 compliant.",
    supports_india: true,
    reliability_score: 9.7,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-07-10"
  },
  {
    id: "tool-linear",
    slug: "linear",
    name: "Linear",
    website_url: "https://linear.app",
    logo_url: "Ⓛ",
    short_description: "Ultra-fast, beautiful issue tracker for modern software teams.",
    long_description: "Linear is a developer-beloved issue tracker designed for speed. High-performance keyboard shortcuts, real-time sync, offline support, clean visual layouts, and instant Git integrations.",
    category: "productivity",
    subcategories: ["Issue Tracker", "Agile Management"],
    capabilities: ["keyboard_navigation", "issue_backlogs", "cycle_tracking"],
    best_for: "Modern tech startups needing an agile project manager that is fast and minimalist.",
    not_recommended_for: "Non-technical marketing calendars needing massive visual photo grids.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 8,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 250 active issues. Standard tier starts at $8/month per member.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["github", "slack", "make", "zapier", "n8n", "pipedream"],
    import_formats: ["CSV", "Jira"],
    export_formats: ["CSV", "JSON"],
    supported_platforms: ["Web", "Mac", "Windows", "iOS", "Android"],
    technical_difficulty: "beginner",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Highly secure, private databases, encrypted logs.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.8,
    verification_status: "verified",
    last_verified_at: "2026-07-07"
  },
  {
    id: "tool-trello",
    slug: "trello",
    name: "Trello",
    website_url: "https://trello.com",
    logo_url: "📋",
    short_description: "Simple visual Kanban board and team project coordinator.",
    long_description: "Trello is the simplest visual card-board coordinator. Users move tasks chronologically across Lists (To Do, Doing, Done) with visual drag-and-drop actions.",
    category: "productivity",
    subcategories: ["Kanban Board", "Task Manager"],
    capabilities: ["kanban_dragging", "card_labeling", "team_assignments"],
    best_for: "Simple visual workflows, content calendar lists, and individual todo tracking.",
    not_recommended_for: "Highly complex software backlogs with dependency trees (use Jira/Linear).",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 5,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 10 boards. Standard starts at $5/month per user.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["slack", "google-sheets", "make", "zapier", "n8n"],
    import_formats: ["CSV"],
    export_formats: ["JSON", "CSV"],
    supported_platforms: ["Web", "Mac", "Windows", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "medium",
    data_retention_notes: "Hosted under Atlassian's secure consumer cloud.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9,
    verification_status: "verified",
    last_verified_at: "2026-05-12"
  },
  {
    id: "tool-google-drive",
    slug: "google-drive",
    name: "Google Drive",
    website_url: "https://google.com/drive",
    logo_url: "📁",
    short_description: "Cloud storage, file sharing, and workspace document backup.",
    long_description: "Google Drive hosts all digital assets, slides, documents, and spreadsheets securely in the cloud. Extensive automation capabilities allow folder uploads to trigger AI scanning actions.",
    category: "productivity",
    subcategories: ["Cloud Storage", "Asset Management"],
    capabilities: ["file_hosting", "shared_directories", "document_viewing"],
    best_for: "Backing up documents, sharing dynamic folders, and serving as a central asset store.",
    not_recommended_for: "Hosting database indexes or low-latency binary assets.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: false,
    starting_monthly_price: 2,
    pricing_currency: "USD",
    pricing_notes: "Free 15GB of shared storage. Business Google One plans start at $2/month.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["gmail", "google-sheets", "make", "zapier", "n8n", "slack"],
    import_formats: ["All Files"],
    export_formats: ["All Files"],
    supported_platforms: ["Web", "Mac", "Windows", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Protected by Google's multi-layered enterprise physical and virtual security.",
    supports_india: true,
    reliability_score: 10,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-07-01"
  },
  {
    id: "tool-calendly",
    slug: "calendly",
    name: "Calendly",
    website_url: "https://calendly.com",
    logo_url: "📅",
    short_description: "Automated booking engine and appointment scheduling link.",
    long_description: "Calendly integrates with user calendars to allow external clients to schedule video calls, meetings, or consulting events instantly, avoiding back-and-forth emails.",
    category: "productivity",
    subcategories: ["Calendar", "Scheduler"],
    capabilities: ["meeting_booking", "calendar_sync", "automated_invites"],
    best_for: "Automating consulting slots, support meetings, and direct sales demo scheduling.",
    not_recommended_for: "Complex project management task flows.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 10,
    pricing_currency: "USD",
    pricing_notes: "Free basic scheduling link. Essentials plan is $10/month per seat.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["zoom", "google-sheets", "make", "zapier", "n8n", "slack"],
    import_formats: ["ICS"],
    export_formats: ["CSV", "JSON"],
    supported_platforms: ["Web", "iOS", "Android"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Maintains calendar invites securely, encrypted at rest.",
    supports_india: true,
    reliability_score: 9.9,
    editorial_quality_score: 9.5,
    verification_status: "verified",
    last_verified_at: "2026-06-18"
  },
  {
    id: "tool-typeform",
    slug: "typeform",
    name: "Typeform",
    website_url: "https://typeform.com",
    logo_url: "📝",
    short_description: "Beautiful, high-conversion conversational web forms and surveys.",
    long_description: "Typeform designs forms that show only one question at a time. Exceptional conversion rates, highly aesthetic layouts, and rich webhook payloads to trigger post-intake automations.",
    category: "productivity",
    subcategories: ["Form Builder", "Surveys"],
    capabilities: ["form_intake", "conversational_ui", "survey_analytics"],
    best_for: "Capturing customer feedback, client design briefs, and clean lead intakes.",
    not_recommended_for: "Complex relational data calculations or spreadsheet-like edits.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 25,
    pricing_currency: "USD",
    pricing_notes: "Free basic forms (10 responses/mo limit). Basic plan is $25/month paid annually.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["google-sheets", "slack", "make", "zapier", "n8n", "notion"],
    import_formats: ["JSON"],
    export_formats: ["CSV", "XLSX", "JSON"],
    supported_platforms: ["Web"],
    technical_difficulty: "non_technical",
    no_code_friendly: true,
    open_source: false,
    self_hostable: false,
    privacy_level: "high",
    data_retention_notes: "Highly secure cloud database, HIPAA and GDPR compliance available on high tiers.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.7,
    verification_status: "verified",
    last_verified_at: "2026-07-02"
  },
  {
    id: "tool-retool",
    slug: "retool",
    name: "Retool",
    website_url: "https://retool.com",
    logo_url: "🛠️",
    short_description: "Fast visual drag-and-drop builder to compile internal business tools.",
    long_description: "Retool is a developer-centric low-code IDE. Drag and drop UI elements (tables, charts, search bars) and write JavaScript/SQL queries to bind them directly to database schemas and APIs.",
    category: "development",
    subcategories: ["Low-code Builder", "Internal Tools"],
    capabilities: ["ui_compiling", "database_queries", "api_binding"],
    best_for: "Developers needing to build custom internal admin screens, CSV uploader boards, or user managers quickly.",
    not_recommended_for: "Public consumer-facing website marketing sites.",
    pricing_type: "freemium",
    free_plan_available: true,
    free_trial_available: true,
    starting_monthly_price: 10,
    pricing_currency: "USD",
    pricing_notes: "Free for up to 5 builders with basic elements. Team plan starts at $10/month per user.",
    api_available: true,
    webhooks_available: true,
    direct_integrations: ["supabase", "github", "slack", "make", "zapier"],
    import_formats: ["JSON"],
    export_formats: ["JSON", "CSV"],
    supported_platforms: ["Web", "Cloud", "Self-hosted"],
    technical_difficulty: "intermediate",
    no_code_friendly: false,
    open_source: false,
    self_hostable: true,
    privacy_level: "high",
    data_retention_notes: "Does not store user data directly; queries database directly. Self-hosting ensures pure security.",
    supports_india: true,
    reliability_score: 9.8,
    editorial_quality_score: 9.7,
    verification_status: "verified",
    last_verified_at: "2026-07-09"
  }
];

export const INITIAL_INTEGRATIONS: ToolIntegration[] = [
  {
    id: "int-make-google-sheets",
    source_tool_slug: "make",
    target_tool_slug: "google-sheets",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "easy",
    requires_paid_plan: false,
    notes: "Make.com has native connectors to read, append, and update cells in Google Sheets instantly.",
    documentation_url: "https://www.make.com/en/integrations/google-sheets"
  },
  {
    id: "int-make-slack",
    source_tool_slug: "make",
    target_tool_slug: "slack",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "easy",
    requires_paid_plan: false,
    notes: "Make.com features native trigger blocks to post text reports and visual attachments directly to Slack channels.",
    documentation_url: "https://www.make.com/en/integrations/slack"
  },
  {
    id: "int-make-notion",
    source_tool_slug: "make",
    target_tool_slug: "notion",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "medium",
    requires_paid_plan: false,
    notes: "Requires sharing the Notion database with the Make.com integration token, after which records can be dynamically mapped.",
    documentation_url: "https://www.make.com/en/integrations/notion"
  },
  {
    id: "int-zapier-google-sheets",
    source_tool_slug: "zapier",
    target_tool_slug: "google-sheets",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "easy",
    requires_paid_plan: false,
    notes: "Zapier's most popular native connection. Appends rows immediately upon trigger operations.",
    documentation_url: "https://zapier.com/apps/google-sheets/integrations"
  },
  {
    id: "int-zapier-slack",
    source_tool_slug: "zapier",
    target_tool_slug: "slack",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "easy",
    requires_paid_plan: false,
    notes: "Zapier lets users dispatch automated Slack messages directly when target spreadsheet triggers fire.",
    documentation_url: "https://zapier.com/apps/slack/integrations"
  },
  {
    id: "int-n8n-supabase",
    source_tool_slug: "n8n",
    target_tool_slug: "supabase",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "medium",
    requires_paid_plan: false,
    notes: "n8n has full native SQL query and Auth management nodes for Supabase.",
    documentation_url: "https://n8n.io/integrations/supabase/"
  },
  {
    id: "int-make-gmail",
    source_tool_slug: "make",
    target_tool_slug: "gmail",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "easy",
    requires_paid_plan: false,
    notes: "Send or parse emails dynamically using Make's native Google OAuth flow.",
    documentation_url: "https://www.make.com/en/integrations/google-email"
  },
  {
    id: "int-buffer-canva",
    source_tool_slug: "canva",
    target_tool_slug: "buffer",
    connection_type: "direct",
    status: "verified",
    setup_difficulty: "easy",
    requires_paid_plan: false,
    notes: "Export designs directly from Canva into Buffer's social publishing queue.",
    documentation_url: "https://support.buffer.com/article/327-canva-integration"
  },
  {
    id: "int-github-vercel",
    source_tool_slug: "github",
    target_tool_slug: "vercel",
    connection_type: "native",
    status: "verified",
    setup_difficulty: "easy",
    requires_paid_plan: false,
    notes: "Vercel listens for repository commits on GitHub and triggers automatic production build deployments.",
    documentation_url: "https://vercel.com/docs/deployments/git"
  }
];
